---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-backend
  template:
    metadata:
      labels:
        app: ecommerce-backend
    spec:
      containers:
      - name: backend
        image: anchu72docker/products-backend:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-svc
spec:
  type: ClusterIP
  selector:
    app: ecommerce-backend
  ports:
  - port: 8080
    targetPort: 8080

...
