---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: productsapideployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: products
 template:
  metadata:
   name: products
   labels:
     app: products
  spec:
    containers:
    - name: productscontainer
      image: anchu72docker/products
      ports:
      - containerPort: 8080
   env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://database.c5kaq8uocoac.ap-south-1.rds.amazonaws.com:3306/vinodses_ecomm"
        - name: SPRING_DATASOURCE_USERNAME
          value: "admin"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "dbadmin123"
---
apiVersion: v1
kind: Service
metadata:
 name: productssvc
spec:
  type: LoadBalancer
  selector:
   app: products
  ports:
   - port: 80
     targetPort: 8080
...
